# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-07 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20180506_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to='img/profile'),
        ),
    ]
