# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-07 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_records_img_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='img_profile',
            new_name='foto_profile',
        ),
    ]
