# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-07 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20180507_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='foto_profile',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
